modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="fantasy_fusions"
version="1.0.0"
displayName="Fantasy Fusions"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="JesusChrist, MCreator"

[[dependencies.fantasy_fusions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




